package vga_pkg;

  import uvm_pkg::*;
  `include "uvm_macros.svh"

  `include "common/transactions/base_transactions/bit_transaction.sv"
  `include "common/transactions/base_transactions/reset_transaction.sv"
  `include "common/transactions/base_transactions/screen_transaction.sv"
  `include "common/transactions/base_transactions/timing_transaction.sv"
  `include "common/transactions/bundle_transactions/bit_rst_transaction.sv"
  `include "common/transactions/bundle_transactions/screen_button_transaction.sv"
  `include "common/transactions/base_transactions/paddle_transaction.sv"
  `include "common/transactions/bundle_transactions/screen_button_paddle_transaction.sv"
  `include "common/transactions/base_transactions/ball_transaction.sv"
  `include "common/transactions/bundle_transactions/screen_buttons_transaction.sv"
  `include "common/transactions/base_transactions/vga_transaction.sv"
  `include "common/transactions/bundle_transactions/game_transaction.sv"
  `include "common/sequences/bit_sequence.sv"
  `include "common/sequences/reset_sequence.sv"
  `include "common/sequencers/bit_sequencer.sv"
  `include "common/sequencers/reset_sequencer.sv"
  `include "common/drivers/vga_frame_driver.sv"
  `include "common/drivers/reset_driver.sv"
  `include "common/monitors/vga_monitor.sv"
  `include "common/coverage/vga_coverage.sv"
  `include "classes/vga_agent.sv"
  `include "block/Synchronizer/classes/synchronizer_predictor.sv"
  `include "block/Debouncer/classes/debouncer_predictor.sv"
  `include "block/Paddle/classes/paddle_predictor.sv"
  `include "block/Ball/classes/ball_predictor.sv"
  `include "block/GameManager/classes/game_manager_predictor.sv"
  `include "block/GraphicsManager/classes/graphics_manager_predictor.sv"
  `include "block/VGATiming/classes/timing_predictor.sv"
  `include "block/GameManager/classes/game_manager_scoreboard.sv"
  `include "block/VGATiming/classes/timing_scoreboard.sv"
  `include "classes/vga_env.sv"
  `include "classes/vga_test.sv"

endpackage
